language: node_js
node_js:
- 8.1.3
services:
  - postgresql
branches:
  only:
    - development
cache:
  directories:
   - "node_modules"
env:
  - TEST_DBURL=TEST_URL
before_script:
  - psql -c 'create database Event-Manager-Test;' -U postgresql
  
script:
  - npm test
after_success:
  - npm run coverage



