language: node_js
node_js:
- 8.1.3
services:
  - postgresql
branches:
  only:
    - development
cache:
  directories:
   - "node_modules"
env:
  - TEST_DBURL=TEST_URL

script:
  - npm test

before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
after_success:
  - npm run coverage



